# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">=1.9.1"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Mount magma directory in all VMs
  config.vm.synced_folder "../..", "/home/vagrant/magma"

  config.vm.define :magma, primary: true do |magma|
    # Get our prepackaged box from the atlas cloud, based on
    # - debian/contrib-jessie64
    # - linux kernel from debian jessie backports
    # - updated vbguest-tool
    config.vm.box = "magmacore/magma_dev"
    config.vm.box_version = "1.1.20210618"
     # Enable Dynamic Swap Space to prevent Out of Memory crashes
    config.vm.provision :shell, inline: "swapoff -a && fallocate -l 4G /swapfile && chmod 0600 /swapfile && mkswap /swapfile && swapon /swapfile && echo '/swapfile none swap sw 0 0' >> /etc/fstab && swapon -a"
    config.vm.provision :shell, inline: "echo vm.swappiness = 10 >> /etc/sysctl.conf && echo vm.vfs_cache_pressure = 50 >> /etc/sysctl.conf && sysctl -p"
    config.vm.provision :shell, inline: "if ! [ -x /usr/bin/bazel ]; then wget --progress=dot:giga https://github.com/bazelbuild/bazelisk/releases/download/v1.10.0/bazelisk-linux-amd64 && chmod +x bazelisk-linux-amd64 && cp bazelisk-linux-amd64 /usr/bin/bazel; fi"
    magma.vbguest.auto_update = false

    magma.vm.provider "virtualbox" do |vb|
      vb.name = "magma-dev"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", ENV.fetch("MAGMA_DEV_MEMORY_MB", "8192")]
      vb.customize ["modifyvm", :id, "--cpus", ENV.fetch("MAGMA_DEV_CPUS", "4")]
    end
  end
