---
name: "Bazel Build & Test"
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - master
    paths:
      - .github/workflows/bazel.yml
  schedule:
    # Run four times a day to build bazel cache
    - cron: '0 0,6,12,18 * * *'
env:
  BAZEL_BASE_IMAGE: "ghcr.io/magma/magma/bazel-base:latest"
  # In case of poisoned caches the CACHE_KEY can be changed.
  CACHE_KEY: bazel-workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  path_filter:
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.changes.outputs.files_changed }}
    steps:
      # Need to get git on push event
      - uses: dorny/paths-filter@v2
        if: github.event_name == 'pull_request'
        id: changes
        with:
          filters: |
            files_changed:
              - '.github/workflows/bazel.yml'
              - 'orc8r/gateway/**'
              - 'orc8r/protos/**'
              - 'lte/gateway/**'
              - 'lte/protos/**'
              - 'src/go/**'
              - '**/BUILD'
              - '**/*.BUILD'
              - '**/*.bazel'
              - '**/*.bzl'

  bazel_build:
    needs: path_filter
    # Only run workflow if this is a scheduled run on master branch,
    # or a pull_request that skip-duplicate-action wants to run again.
    if: |
      (github.event_name == `schedule` && github.ref == 'refs/heads/master')
        || ${{ needs.path_filter.outputs.files_changed == 'true' }}
    name: Bazel Build Job `bazel build //...`
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        shell: bash
        run: |
          echo "Available storage before:"
          df -h
          echo "Removing /usr/share/dotnet, /usr/local/lib/android, /opt/ghc"
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          echo "Available storage after:"
          df -h
      - name: Check Out Repo
        # This is necessary for overlays into the Docker container below.
        uses: actions/checkout@v2
      - name: Setup Bazel Base Image
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.BAZEL_BASE_IMAGE }}
          options: --pull always
          # Run a simple echo command to pull down the image. This makes it a bit more clear how much time is spent on building Magma and not pulling down the image.
          run: |
            echo "Pulled the bazel base image!"
      - name: Setup bazel config of read and write
        uses: addnab/docker-run-action@v3
        if: |
          (github.repository == 'lkreutzer/magma' && github.ref == 'refs/heads/bazel_workflow_remote_caching')
        with:
          image: ${{ env.BAZEL_BASE_IMAGE }}
          # TODO: Remove work-around mount of Github workspace to /magma (https://github.com/addnab/docker-run-action/issues/11)
          options: -v ${{ github.workspace }}:/magma/
          run: |
            cd /magma
            sed --in-place -e s@~~MAGMA_REMOTE_USER~~@${{ secrets.MAGMA_REMOTE_USER }}@ .bazelrc
            sed --in-place -e s@~~MAGMA_REMOTE~~@${{ secrets.MAGMA_REMOTE }}@ .bazelrc
            sed --in-place -e s@~~CACHE_KEY~~@${{ env.CACHE_KEY }}@ .bazelrc
            cat .bazelrc
            ln -fs bazel/bazelrcs/remote_caching_rw.bazelrc /etc/bazelrc
      - name: Setup bazel config for read-only
        uses: addnab/docker-run-action@v3
        if: |
          (github.repository != 'lkreutzer/magma' || github.ref != 'refs/heads/bazel_workflow_remote_caching')
        with:
          image: ${{ env.BAZEL_BASE_IMAGE }}
          # TODO: Remove work-around mount of Github workspace to /magma (https://github.com/addnab/docker-run-action/issues/11)
          options: -v ${{ github.workspace }}:/magma/
          run: |
            cd /magma
            sed --in-place -e s@~~CACHE_KEY~~@${{ env.CACHE_KEY }}@ .bazelrc
            cat .bazelrc
            ln -fs bazel/bazelrcs/remote_caching_ro.bazelrc /etc/bazelrc
      - name: Run `bazel build //...`
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.BAZEL_BASE_IMAGE }}
          # TODO: Remove work-around mount of Github workspace to /magma (https://github.com/addnab/docker-run-action/issues/11)
          options: -v ${{ github.workspace }}:/magma/
          run: |
            cd /magma
            bazel build //...
      - name: Build space left after run
        shell: bash
        run: |
          echo "Available storage:"
          df -h

  bazel_test:
    needs: path_filter
    # Only run workflow if this is a scheduled run on master branch,
    # or a pull_request that skip-duplicate-action wants to run again.
    if: |
      (github.event_name == `schedule` && github.ref == 'refs/heads/master')
        || ${{ needs.path_filter.outputs.files_changed == 'true' }}
    name: Bazel Test Job `bazel test //...`
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        shell: bash
        run: |
          echo "Available storage before:"
          df -h
          echo "Removing /usr/share/dotnet, /usr/local/lib/android, /opt/ghc"
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          echo "Available storage after:"
          df -h
      - name: Check Out Repo
        # This is necessary for overlays into the Docker container below.
        uses: actions/checkout@v2
      - name: Setup Bazel Base Image
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.BAZEL_BASE_IMAGE }}
          options: --pull always
          # Run a simple echo command to pull down the image. This makes it a bit more clear how much time is spent on building Magma and not pulling down the image.
          run: |
            echo "Pulled the bazel base image!"
      - name: Setup bazel config of read and write
        uses: addnab/docker-run-action@v3
        if: |
          (github.repository == 'lkreutzer/magma' && github.ref == 'refs/heads/bazel_workflow_remote_caching')
        with:
          image: ${{ env.BAZEL_BASE_IMAGE }}
          # TODO: Remove work-around mount of Github workspace to /magma (https://github.com/addnab/docker-run-action/issues/11)
          options: -v ${{ github.workspace }}:/magma/
          run: |
            cd /magma
            sed --in-place -e s@~~MAGMA_REMOTE_USER~~@${{ secrets.MAGMA_REMOTE_USER }}@ .bazelrc
            sed --in-place -e s@~~MAGMA_REMOTE~~@${{ secrets.MAGMA_REMOTE }}@ .bazelrc
            sed --in-place -e s@~~CACHE_KEY~~@${{ env.CACHE_KEY }}@ .bazelrc
            cat .bazelrc
            ln -fs bazel/bazelrcs/remote_caching_rw.bazelrc /etc/bazelrc
      - name: Setup bazel config for read-only
        uses: addnab/docker-run-action@v3
        if: |
          (github.repository != 'lkreutzer/magma' || github.ref != 'refs/heads/bazel_workflow_remote_caching')
        with:
          image: ${{ env.BAZEL_BASE_IMAGE }}
          # TODO: Remove work-around mount of Github workspace to /magma (https://github.com/addnab/docker-run-action/issues/11)
          options: -v ${{ github.workspace }}:/magma/
          run: |
            cd /magma
            sed --in-place -e s@~~CACHE_KEY~~@${{ env.CACHE_KEY }}@ .bazelrc
            cat .bazelrc
            ln -fs bazel/bazelrcs/remote_caching_ro.bazelrc /etc/bazelrc
      - name: Run `bazel test //...`
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.BAZEL_BASE_IMAGE }}
          # TODO: Remove work-around mount of Github workspace to /magma (https://github.com/addnab/docker-run-action/issues/11)
          options: -v ${{ github.workspace }}:/magma/ -v ${{ github.workspace }}/lte/gateway/configs:/etc/magma
          run: |
            cd /magma
            bazel test //... \
              --cache_test_results=no \
              --test_output=errors
      - name: Run `bazel run //:check_starlark_format`
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.BAZEL_BASE_IMAGE }}
          # TODO: Remove work-around mount of Github workspace to /magma (https://github.com/addnab/docker-run-action/issues/11)
          options: -v ${{ github.workspace }}:/magma/
          run: |
            cd /magma
            bazel run //:check_starlark_format
      - name: Test python services for missing modules
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.BAZEL_BASE_IMAGE }}
          # TODO: Remove work-around mount of Github workspace to /magma (https://github.com/addnab/docker-run-action/issues/11)
          options: -v ${{ github.workspace }}:/magma/
          run: |
            cd /magma
            bazel/scripts/test_python_service_imports.sh
      - name: Build space left after run
        shell: bash
        run: |
          echo "Available storage:"
          df -h
