# Copyright 2022 The Magma Authors.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: PR Check DCO
on:
  pull_request_target: null

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  dco_check_job:
    name: DCO Check
    runs-on: ubuntu-20.04
    steps:
      - name: Get PR Commits
        id: get-pr-commits
        uses: tim-actions/get-pr-commits@c64db31d359214d244884dd68f971a110b29ab83 # pin@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: DCO Check
        id: dco-check
        if: ${{ ! startsWith(github.event.pull_request.title, 'Revert ') }}
        uses: tim-actions/dco@f2279e6e62d5a7d9115b0cb8e837b777b1b02e21 # pin@master
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3.1.0
        if: always()
      - uses: ./.github/workflows/composite/comment-on-pr
        if: always()
        env:
          check-type: Developer Certificate of Origin (DCO)
          check-documentation: See [instructions on Developer Certificate of Origin (DCO) and sign-off](https://github.com/magma/magma/wiki/Contributing-Code#signed-off-commits).
        with:
          check-type: ${{ env.check-type }}
          check-documentation: ${{ env.check-documentation }}
          job-status: ${{ steps.dco-check.outcome }}
