---

name: LTE integ test bazel

on:
  workflow_dispatch: null

jobs:
  lte-integ-test-bazel:
    if: github.repository_owner == 'LKreutzer' || github.event_name == 'workflow_dispatch'
    runs-on: macos-10.15
    env:
      SHA: ${{ github.event.workflow_run.head_commit.id || github.sha }}
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # pin@v2
        with:
          ref: ${{ env.SHA }}
      - name: Failure
        run: |
          exit 1
      - name: Notify failure to slack
        if: failure() && github.repository_owner == 'LKreutzer'
        uses: Ilshidur/action-slack@689ad44a9c9092315abd286d0e3a9a74d31ab78a # pin@2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_BAZEL_CI }}
          SLACK_USERNAME: "LTE integ tests bazel"
          SLACK_AVATAR: ":boom:"
        with:
          args: "TESTING! Bazel LTE integration test failed in run: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
